### ISSUE TITLE
New Fabric Version

### ISSUE THREAD

**Issue by Reffler** [Scherso/NotSoEssential#12]
Hey, I would like to say your mod is very underrated at the moment! I do believe the idea is amazing, and it works well, but I would like to suggest an updated version to something like Fabric 1.19.2. 

I tested and loved your mod (default Essential is too bloated and kind of sketchy), but I won't be using it as I prefer playing more updated Fabric versions.

Thank you regardless, and keep up! :)

**Comment by Scherso** [comment]
Thanks for the feedback, I'd love to port this to 1.19.2, I just need to setup a development environment for that version. I'll try to release an updated version before the new year.

**Comment by linux-leo** [comment]
backporting to 1.12 whatever you add (remove?) in the new version would be also very appreciated, but take your time.

Amazing Mod.

**Comment by Scherso** [comment]
Oh yeah, of course I'll make sure both versions have the same features as each other, and if I find anything new I'll be sure to update both versions.

**Comment by Scherso** [comment]
Wait there's sound settings? I never realized. I'll just remove that with the next update, feel free to give me lists of things to remove, I don't notice sometimes lol

**Comment by Reffler** [comment]
Thanks for letting us know! And don't worry, take your time. I am sure a lot of people would rather use this mod as opposed to default Essential.

I am curious about one thing tho (I'm not an experienced programmer so maybe that sounds dumb but anyway):

How do you manage to modify Essential considering it is closed source?

**Comment by Scherso** [comment]
Even though Essential is closed source, it isn't obfuscated, meaning I'm able to de-compile it, and read the de-compiled code as though it was the source. Because Java is compiled to byte-code, I can just use the [ObjectWeb ASM](https://asm.ow2.io/) library to manipulate the byte-code (Java's instructions) to do something different from the original thing it was doing. 

If you want to look at the basics, there's a book [here](https://asm.ow2.io/asm4-guide.pdf). It's pretty cool!

**Comment by Reffler** [comment]
Ohh that's clever! Good to know such workaround is possible. Thanks for the clarification!

**Comment by Scherso** [comment]
If you want to check progress, I've made some progress on the [test](https://github.com/Scherso/NotSoEssential/tree/test) branch, All that's really left now is to figure out how to inject into Essential's jarfile without having to first, change it's directory from `.minecraft/essential/` to `.minecraft/mods`.

**Comment by Reffler** [comment]
Looking promising, it's really nice to see what I suggested was taken into account. And damn, it might actually be done before new year like you said, good job man

**Comment by Scherso** [comment]
If I per-release before 12:00 AM EST does that count :joy:

**Comment by Scherso** [comment]
welp

**Comment by Reffler** [comment]
haha it's going well regardless!

**Comment by Scherso** [comment]
Once I’ve found a way to inject into Essential without moving any file locations, there will be a full release with new features for both legacy Forge and Fabric.

If you think it would be a good idea to make a pre-release with the progress so far, then I’ll take that advice, but at the moment, it’s required that you move Essential’s Jar-file from your `.minecraft/essential` directory to `.minecraft/mods` to ensure that this mod will work. I don’t want to make a full release on a mod that’s hard to use, but a pre-release may be a good idea.

**Comment by YumatanGames** [comment]
Hey sorry to message on a closed issue, but I'm really interested in the Fabric 1.19.2 version... Is it available? This mod is incredibly necessary to make the Essential mod, actually essential. :D

**Comment by Scherso** [comment]
> Hey sorry to message on a closed issue, but I'm really interested in the Fabric 1.19.2 version... Is it available? This mod is incredibly necessary to make the Essential mod, actually essential. :D

It’s not very user friendly to install, but I can provide a JarFile for 1.19.2 if you need it later today when I can compile it.
