### ISSUE TITLE
Newest version (1.0.2) crashes when trying to access multiplayer with latest version of Patcher mod

### ISSUE THREAD

**Issue by HyperLemons** [Scherso/NotSoEssential#16]
Minecraft version 1.8.9 on Forge, using Prism Launcher

Full launch log: https://mclo.gs/pdneQk4
Crash log: https://mclo.gs/aWXxTs2

Latest release of Patcher mod (1.8.6, this is the version of the mod not the version of Minecraft): https://sk1er.club/mods/patcher

Using release 1.0.0 (https://github.com/Scherso/NotSoEssential/releases/tag/v1.0.0) does not give this problem.

**Comment by Scherso** [comment]
Testing now

**Comment by Scherso** [comment]
https://streamable.com/ppi5k3

Isn't happening for me, however, I'm gonna try and fix the stack frame issue you pointed out in the crash log.

**Comment by Scherso** [comment]
Fixed with latest comimt [`0acec195fcfcbe6394b2405f9f80e7508f4a51ca`](https://github.com/Scherso/NotSoEssential/commit/0acec195fcfcbe6394b2405f9f80e7508f4a51ca).
