### ISSUE TITLE
Crash on /nse

### ISSUE THREAD

**Issue by PrincessAkira** [Scherso/NotSoEssential#7]
Log here:
https://pastebin.com/raw/2P0KESvq

**Comment by Scherso** [comment]
First issue! Thank you for opening an issue, I'll be sure to fix this as soon as possible

**Comment by Scherso** [comment]
Looks like the text component I'm using for multi-version support clashes somewhat with other mods, I'm assuming labymod, I'll move to a different method of adding a chat message

**Comment by Scherso** [comment]
I’ve just removed the command all together with the new update, it served no purpose really.
