### ISSUE TITLE
Essentials Updated

### ISSUE THREAD

**Issue by websterwh** [Scherso/NotSoEssential#9]
Essentials Mod has updated so NotSoEssential doesn't work properly anymore.

**Comment by Mixces** [comment]
This mod isn't needed anymore since the new Essential update offers the option to completely disable/hide the buttons + cosmetics and such.

**Comment by websterwh** [comment]
Ok, thanks

**Comment by Scherso** [comment]
@Mixces Shut up, still gonna make this work today. Just to prove you wrong cause I’m petty like that.

@websterwh to the rescue no worries.

**Comment by Scherso** [comment]
I’ve made changes to have it work with the new update, you can view them [here](https://github.com/Scherso/NotSoEssential/pull/10) 👍

**Comment by websterwh** [comment]
Now I can be cool again
